# example-node[123]-bmh-secret & assisted-deployment-pull-secret need to be created under same namespace example-3node
---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "site3"
  namespace: "site3"
spec:
  baseDomain: "example.com"
  pullSecretRef:
    name: "pullsecret-cluster-site3"
  clusterImageSetNameRef: "acmopenshift4.12.25"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDRQb+spDn5O3ER5gyuRJV3pE4/OA5cp4kJbTnHh7u6ipqdF47jPwH+bCT0k/+dn8x2UAyts9mR8Vqdb7/vMBgAyceBvXp4ku/leIivwheWI3cilzNtLUm21sUQfN07aGKvCiA1bYfv3xR92yTgxFSKuNUpLnKCWA015QUKmVJp+EmRe5GuEbr4NYQvJ4PHikpjWG0x+yXBhLrL0RvODYS6Sw8RlsBFbhJFeMPKPqQcJCRzGvVLWBuQiJyMiQzB/F/+fmlHswS9w6PlEScHuIdvX5bK8Eod2YFx1lMGNHQTSphCmrhJQ6yTVoW+YQyX8g2AGeDl34mRuhcT96r0JbikIsi+3X48kdON9dqz6TgeCAwxWl0pSnmLwlmB00X7dwEF7XnKESqBB7qZP86q821HYcK0n6Xvt5wnPUJXlkp/6M1WTUm2zJwAIuxp+Y0EMpEFWi+9VmOWk5usiGOKzRseHYyP1o39apoYmfPRO64AyyMHOuMYoNAVpvHH5dnm9ZE= m3@hpe-dl380gen10-02.hpe2.lab.eng.bos.redhat.com"
  clusters:
  - clusterName: "site3"
    networkType: "OVNKubernetes"
    clusterLabels:
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples in ../policygentemplates:
      # ../policygentemplates/common-ranGen.yaml will apply to all clusters with 'common: true'
      common: true
      # ../policygentemplates/group-du-3node-ranGen.yaml will apply to all clusters with 'group-du-3node: ""'
      #group-du-3node: ""
      # ../policygentemplates/example-multinode-site.yaml will apply to all clusters with 'sites: "example-multinode"'
      # Normally this should match or contain the cluster name so it only applies to a single cluster
      #sites : "example-multinode"
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    # For 3-node and standard clusters with static IPs, the API and Ingress IPs must be configured here
    apiVIP: 192.168.40.5
    ingressVIP: 192.168.40.4
    serviceNetwork:
      - 172.30.0.0/16
   # additionalNTPSources:
    #  - 1111:2222:3333:4444::2
    # Optionally; This can be used to override the KlusterletAddonConfig that is created for this cluster:
    #crTemplates:
    #  KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    # Optionally; This can be used to to configure desired BIOS setting on all nodes in this cluster:
    #biosConfigRef:
    #  filePath: "example-hw.profile"
    nodes:
      - hostName: "node1.example.com"
        role: "master"
        bmcAddress: "idrac-virtualmedia+https://[1111:2222:3333:4444::bbbb:1]/redfish/v1/Systems/System.Embedded.1"
        bmcCredentialsName:
          name: "example-node1-bmh-secret"
        bootMACAddress: "AA:BB:CC:DD:EE:11"
        # Use UEFISecureBoot to enable secure boot for this node
        bootMode: "UEFI"
        rootDeviceHints:
          hctl: '0:1:0'
        nodeNetwork:
          interfaces:
            - name: eno1
              macAddress: "AA:BB:CC:DD:EE:11"
          config:
            interfaces:
              - name: eno1
                type: ethernet
                state: up
                macAddress: "AA:BB:CC:DD:EE:11"
                ipv4:
                  enabled: false
                ipv6:
                  enabled: true
                  address:
                  - ip: 1111:2222:3333:4444::aaaa:1
                    prefix-length: 64
            dns-resolver:
              config:
                search:
                - example.com
                server:
                - 1111:2222:3333:4444::2
            routes:
              config:
              - destination: ::/0
                next-hop-interface: eno1
                next-hop-address: 1111:2222:3333:4444::1
                table-id: 254
      - hostName: "example-node2.example.com"
        role: "master"
        bmcAddress: "idrac-virtualmedia+https://[1111:2222:3333:4444::bbbb:2]/redfish/v1/Systems/System.Embedded.1"
        bmcCredentialsName:
          name: "example-node2-bmh-secret"
        bootMACAddress: "AA:BB:CC:DD:EE:22"
        bootMode: "UEFI"
        rootDeviceHints:
          hctl: '0:1:0'
        nodeNetwork:
          interfaces:
            - name: eno1
              macAddress: "AA:BB:CC:DD:EE:22"
          config:
            interfaces:
              - name: eno1
                type: ethernet
                state: up
                macAddress: "AA:BB:CC:DD:EE:22"
                ipv4:
                  enabled: false
                ipv6:
                  enabled: true
                  address:
                  - ip: 1111:2222:3333:4444::aaaa:2
                    prefix-length: 64
            dns-resolver:
              config:
                search:
                - example.com
                server:
                - 1111:2222:3333:4444::2
            routes:
              config:
              - destination: ::/0
                next-hop-interface: eno1
                next-hop-address: 1111:2222:3333:4444::1
                table-id: 254
      - hostName: "example-node3.example.com"
        role: "master"
        bmcAddress: "idrac-virtualmedia+https://[1111:2222:3333:4444::bbbb:3]/redfish/v1/Systems/System.Embedded.1"
        bmcCredentialsName:
          name: "example-node3-bmh-secret"
        bootMACAddress: "AA:BB:CC:DD:EE:33"
        bootMode: "UEFI"
        rootDeviceHints:
          hctl: '0:1:0'
        nodeNetwork:
          interfaces:
            - name: eno1
              macAddress: "AA:BB:CC:DD:EE:33"
          config:
            interfaces:
              - name: eno1
                type: ethernet
                state: up
                macAddress: "AA:BB:CC:DD:EE:33"
                ipv4:
                  enabled: false
                ipv6:
                  enabled: true
                  address:
                  - ip: 1111:2222:3333:4444::aaaa:3
                    prefix-length: 64
            dns-resolver:
              config:
                search:
                - example.com
                server:
                - 1111:2222:3333:4444::2
            routes:
              config:
              - destination: ::/0
                next-hop-interface: eno1
                next-hop-address: 1111:2222:3333:4444::1
                table-id: 254
